### ISSUE TITLE
Failure to start: NameError: name 'manager' is not defined

### ISSUE THREAD

**Issue by satmandu** [fredley/raspi-turntouch#6]
```
Mar 08 08:05:01 chip systemd[1]: Started TurnTouch Pi Service.
Mar 08 08:05:04 chip python3[29774]: Traceback (most recent call last):
Mar 08 08:05:04 chip python3[29774]:   File "/home/satmandu/turntouch/monitor.py", line 204, in <module>
Mar 08 08:05:04 chip python3[29774]:     manager=manager,
Mar 08 08:05:04 chip python3[29774]: NameError: name 'manager' is not defined
Mar 08 08:05:04 chip systemd[1]: turntouch.service: Main process exited, code=exited, status=1/FAILURE
Mar 08 08:05:04 chip systemd[1]: turntouch.service: Failed with result 'exit-code'.
```

**Comment by The-Kadweka** [comment]
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    @manager.shell
NameError: name 'manager' is not defined
![Screenshot from 2019-06-30 18-18-07](https://user-images.githubusercontent.com/49676297/60399518-c6c03c00-9b65-11e9-8b4f-9537f1509b15.png)

**Comment by samuelclay** [comment]
It looks like that isn't this code. What are you running?

**Comment by The-Kadweka** [comment]
Python3.6 manager.py shell

**Comment by tedder** [comment]
manage.py is in a directory in your screenshot called "BLOG". There is no manage.py in this project. Why do you think it is apropos to this project?

**Comment by fredley** [comment]
Can you check your environment variable for DJANGO_SETTINGS_MODULE? If you
have another Django project you're working on it could conflict.
